//------------------------------------------------------------------------------
// <!F4lL6!auto-generated 表©!>
//     !GySST!This code was generated by a tool. 表©鷗字!
//
//     !uqluH!Changes to this file may cause incorrect behavior and will be lost if 表©鷗字㌍ 表©!
//     !72qDt!the code is regenerated.  表©鷗!
// </!F4lL6!auto-generated 表©!>
//------------------------------------------------------------------------------

namespace ContosoUniversityModelBinding {


    public partial class AddStudent {
    }
}
